const teachers = [
    {id:"1", name: "Edyta Badura", course: "wychowanie przedszkolne"},
    {id:"2", name: "Barbara Bocek", course: "język angielski, logopedia"},
    {id:"3", name: "Klaudia Brańka", course: "pedagog szkolny, wychowanie do życia w rodzinie"},
    {id:"4", name: "Agnieszka Choińska", course: "plastyka, nauczanie zintegrowane, terapia pedagogiczna"},
    {id:"5", name: "Monika Cieślar", course: "wychowanie przedszkolne"},
    {id:"6", name: "Małgorzata Czyż", course: "biologia, przyroda, wychowawca świetlicy"},
    {id:"7", name: "Aleksandra Chmiel", course: "nauczanie zintegrowane, terapia pedagogiczna"},
    {id:"8", name: "Małgorzata Jurek", course: "religia, logopedia"},
    {id:"9", name: "Izabela	Kobiela", course: "nauczanie zintegrowane"},
    {id:"10", name: "Anna	Kohut", course: "religia"},
    {id:"11", name: "Przemysław	Misiarz", course: "wychowanie fizyczne"},
    {id:"12", name: "Ewelina	Czermak-Najbor", course: "język polski"},
    {id:"13", name: "Beata	Pieńkowska", course: "matematyka"},
    {id:"14", name: "Anna Pieszka", course: "wychowawca świetlicy"},
    {id:"15", name: "Renata Polok", course: "język angielski"},
    {id:"16", name: "Elżbieta Stanieczek", course: "muzyka, bibliotekarz"},
    {id:"17", name: "Krystyna Sztwiertnia", course: "nauczanie zintegrowane, logopedia"},
    {id:"18", name: "ks. Marek Twardzik", course: "religia"},
    {id:"19", name: "Robert Zając", course: "wychowanie fizyczne"},
    {id:"20", name: "Henryk Mróz", course: "geografia"},
    {id:"21", name: "Wiesława Machalica", course: "wychowanie przedszkolne"},
    {id:"22", name: "ks. Jarosław Krutak", course: "religia"},
    {id:"23", name: "Agnieszka Macha", course: "język niemiecki, nauczyciel wspomagający"},
    {id:"24", name: "Marek Walica", course: "informatyka, technika"},
    {id:"25", name: "Andrzej Kloske", course: "doradztwo zawodowe"},
    {id:"26", name: "Joanna Talaga", course: "psycholog szkolny"},
    {id:"27", name: "Magdalena	Dziendziel", course: "historia, wos"},
    {id:"28", name: "Paweł	Burzawa", course: "fizyka"},
    {id:"29", name: "Małgorzata Sadowska-Szklorz", course: "chemia"},
    {id:"30", name: "Monika Droździk", course: "język polski, edukacja dla bezpieczeństwa"},
    {id:"31", name: "Jadwiga Pipień", course: "matematyka"},
    {id:"32", name: "Samuel Gogółka", course: "religia"}
]
export default teachers;