export const GET_NOTICES = 'GET_NOTICES';
export const GET_POSTS = 'GET_POSTS';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';

export const GET_PRESCHOOLR_POSTS = 'GET_PRESCHOOLR_POSTS';
export const SET_PRESCHOOLR_CURRENT_POST = 'SET_PRESCHOOLR_CURRENT_POST';
export const CLEAR_PRESCHOOLR_CURRENT_POST = 'CLEAR_PRESCHOOLR_CURRENT_POST';

export const DATO_TOKEN = 'a88fad30abdf092e4056df62c64811';